### ISSUE TITLE
테스트 케이스 작성

### ISSUE THREAD

**Issue by suubinkim** [fever-time/challenge-backend#48]
- [x] domain
- [x] controller
- [x] repository
- [x] service
- [x] integration

**Comment by JunHo-YH** [comment]
- [ ] Category
- [ ] Certification
- [ ] Challenge
- [ ] ChallengeHistory
- [ ] Comment
- [ ] Feed
- [ ] User

**Comment by JunHo-YH** [comment]
- [ ] CategoryRepository
- [ ] CertificationRepository
- [ ] ChallengeHistroyRepository
- [ ] ChallegeRepository
- [ ] CommentRepository
- [ ] FeedRepository
- [ ] UserRepository

**Comment by JunHo-YH** [comment]
- [ ] CertificationService
- [ ] ChallengeHistoryService
- [ ] ChallengeService
- [ ] CommentService
- [ ] FeedService
- [ ] UserService

**Comment by JunHo-YH** [comment]
Challenge - 준호
